# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 17, 1, 39, 51, 978464)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
